### ISSUE TITLE
While having bloxstrap - installer hangs

### ISSUE THREAD

**Issue by Vlad55432** [Extravi/Bloxshade#10]
Since no one reported, I'm lost
![зображення](https://github.com/Extravi/Bloxshade/assets/78297186/d9c0fcef-9d37-4016-9d33-b71de7959dd2)
![зображення](https://github.com/Extravi/Bloxshade/assets/78297186/b5081a32-6bbd-4531-9c24-7b507e163a92)

**Comment by Vlad55432** [comment]
Well, after I ran one time bloxstrap player in background, roblox with bloxstrap closes and I have this.
![зображення](https://github.com/Extravi/Bloxshade/assets/78297186/9570a7b8-52f9-4e1f-b09f-b6ccc7290925)

**Comment by Extravi** [comment]
You're using a pre-release of Bloxstrap that is not supported by Bloxshade. Please use Bloxstrap version 2.5.4.

**Comment by Extravi** [comment]
https://github.com/pizzaboxer/bloxstrap/releases/tag/v2.5.4

**Comment by Vlad55432** [comment]
> You're using a pre-release of Bloxstrap that is not supported by Bloxshade

makes sense, ty
