### ISSUE TITLE
roblox not starting

### ISSUE THREAD

**Issue by Itsnoklol** [Extravi/Bloxshade#12]
so for some reason i installed it i tried it it worked fine then yesterday i tried playing but roblox wont start anymore i tried to delete roblox all files and bloxshade but it youst dosnt works anymore

**Comment by Extravi** [comment]
when roblox updates you need to click this in settings
![image](https://github.com/Extravi/Installer/assets/98912029/01ac9c80-3cae-4efd-903b-318ac5b92314)
![image](https://github.com/Extravi/Installer/assets/98912029/8ae0fbdc-85c5-4ae4-9e2b-74233cf5f72e)

**Comment by Itsnoklol** [comment]
and then stikl doesnt open

**Comment by Itsnoklol** [comment]
anything else

**Comment by Itsnoklol** [comment]
how do i complytly delete bloxshade where are all the files located

**Comment by Itsnoklol** [comment]
bro i tried everything
