### ISSUE TITLE
Even if it is renamed to "eurotrucks2" I still get the A supported game is required to use this feature error

### ISSUE THREAD

**Issue by therealkiddude** [Extravi/Bloxshade#2]

**Comment by Extravi** [comment]
any anti cheat running on the system may block it from working correctly so if you play valorant and have Vanguard installed. it could be blocking it

**Comment by mrrandom314** [comment]
> any anti cheat running on the system may block it from working correctly so if you play valorant and have Vanguard installed. it could be blocking it

I mean, It has been working for the past 2 days via Ansel, but now it just gives me "A supported game is required to use this feature"

**Comment by Extravi** [comment]
that means Roblox has updated and you need to reinstall

**Comment by mrrandom314** [comment]
> that means Roblox has updated and you need to reinstall 

I have tried that does not work, I can send a video of me clicking on eurotrucks2.exe with the version ID shown as the folder name and still get the error.
