### ISSUE TITLE
having bloxshade installed crashes game when using dolpsol macro

### ISSUE THREAD

**Issue by Alexwasnthere01** [Extravi/Bloxshade#20]
https://github.com/Extravi/Bloxshade/assets/159941834/652d5b1f-b481-495f-9d46-57fbf477476d

**Comment by Extravi** [comment]
is that something meant for Roblox?

**Comment by Alexwasnthere01** [comment]
its a macro thats supposed to move my character around and grab coins and potions it also makes my game rejoin when my game crashes or i dissconnect

**Comment by Extravi** [comment]
if it's looking for RobloxPlayerBeta.exe it won't work because Roblox is renamed to eurotrucks2.exe to support Nvidia Ansel

**Comment by Alexwasnthere01** [comment]
oh ok that might be why

**Comment by Alexwasnthere01** [comment]
thank you
