### ISSUE TITLE
Warning! Roblox installation not found.

### ISSUE THREAD

**Issue by yunotalone** [Extravi/Bloxshade#22]
https://github.com/Extravi/Bloxshade/assets/174419751/a41d37dd-d4c9-4956-bd50-ebc0429e4731

**Comment by yunotalone** [comment]
what should I do?

**Comment by Extravi** [comment]
that happens when your account is not an administrator and you run it under a different administrator account make sure your account is an administrator before running bloxshade

**Comment by yunotalone** [comment]
> это происходит, когда ваша учетная запись не является администратором и вы запускаете его под другой учетной записью администратора. Убедитесь, что ваша учетная запись является администратором, прежде чем запускать bloxshade.

![image](https://github.com/Extravi/Bloxshade/assets/174419751/a168580f-a402-45ce-b89d-a6b2e8b70e0c)

**Comment by yunotalone** [comment]
> that happens when your account is not an administrator and you run it under a different administrator account make sure your account is an administrator before running bloxshade

I have an administrator account

**Comment by Extravi** [comment]
> > that happens when your account is not an administrator and you run it under a different administrator account make sure your account is an administrator before running bloxshade
> 
> I have an administrator account

when you get the UAC prompt please make sure you select your account and not a different user on the computer

**Comment by yunotalone** [comment]
> > > это происходит, когда ваша учетная запись не является администратором и вы запускаете его под другой учетной записью администратора. Убедитесь, что ваша учетная запись является администратором, прежде чем запускать bloxshade.
> > 
> > 
> > У меня есть учетная запись администратора
> 
> Когда вы получите запрос UAC, убедитесь, что вы выбрали свою учетную запись, а не другого пользователя на компьютере.

I no longer have accounts
