### ISSUE TITLE
It does not detect Roblox being installed

### ISSUE THREAD

**Issue by foursplaysroblox** [Extravi/Bloxshade#29]
Idk what to do
![image](https://github.com/user-attachments/assets/6beecb19-9f86-4651-ba4f-76f0510e0268)

**Comment by Extravi** [comment]
run it under your own user as admin

**Comment by foursplaysroblox** [comment]
still did not work even running as admin

**Comment by Extravi** [comment]
yeah but you need to be the account that runs it as admin

**Comment by Extravi** [comment]
if that doesn't work try it with bloxstrap installed
