### ISSUE TITLE
Can't open game filter to disable shaders

### ISSUE THREAD

**Issue by Entropy159** [Extravi/Bloxshade#3]
I was able to successfully install this and use shaders, but now I can't open the game filter menu. The keybind and the overlay button don't do anything, not even give the the unsupported game message. I don't even know how to uninstall Bloxshade.

**Comment by Entropy159** [comment]
I got the game filter menu to open but now it just shows "image sharpening" which I can't even edit.

**Comment by Entropy159** [comment]
It also says I need a supported game when I launch it from the website.

**Comment by Entropy159** [comment]
Okay, I've done a lot of tweaking, and eventually I just reinstalled Roblox, but now I'm back where I started where the shaders are on but I can't toggle them or open the menu.

**Comment by AidenBasseal** [comment]
I'm having the same issue. I accidentally left shaders on when I exited roblox, and because of that, my shaders keep turning on whenever I open roblox.

**Comment by Extravi** [comment]
https://discord.gg/YPSkPp5Q

**Comment by Extravi** [comment]
fix is in faq
