### ISSUE TITLE
Unable to install for none admin local user

### ISSUE THREAD

**Issue by Drefsab** [Extravi/Bloxshade#33]
Hi there,

I am trying to use this on my sons  windows  11 pc, I have microsoft family safety enable so I have my admin account and his local account. When trying to run your installer it tries asks my admin pin, then tries to write to the admin user appdata folder and fails.

If I grant full access to that folder it then fails to detect roblox which is installed on the local user not the admin user. Giving permanent admin is not an option maybe giving the option to point it a roblox location if its not auto detected would be good?

**Comment by Extravi** [comment]
it's because your user must be the admin user

**Comment by Extravi** [comment]
also the installer needs admin to edit the Nvidia folder

**Comment by Extravi** [comment]
like the user that wants to install it has to be admin because it's trying to locate the install for that user

**Comment by Extravi** [comment]
you could however manually rename Roblox to eurotrucks2 and start it from there inside of the Roblox folder after installing bloxshade if you don't want to allow your son to run it as admin
