### ISSUE TITLE
Setup keeps crashing while installing

### ISSUE THREAD

**Issue by ziggmeisterr** [Extravi/Bloxshade#36]
Whenever I try to install the shaders, I press install and it goes through the download process but right before it moves onto the "moving files'' part it just straight up crashes/closes. I don't know how to fix it, I've tried reinstalling the setup and restarting my pc multiple times. Please help. 
Video is too big to send here

**Comment by Extravi** [comment]
probably anti virus software blocking it

**Comment by ziggmeisterr** [comment]
> probably anti virus software blocking it

I disabled the antivirus and it still doesnt work

**Comment by Extravi** [comment]
screenshot and send the error

**Comment by ziggmeisterr** [comment]
> screenshot and send the error

theres no error, it just full on closes, I did the nvidia patch too

**Comment by Extravi** [comment]
you can also send part of its install log located at program files bloxshade and inside that folder install.txt and it should be near the end of the file and it will only show the latest install attempt if you open the setup file again it will delete that log

**Comment by Extravi** [comment]
you can also send part of its install log located at program files bloxshade and inside that filter install.txt and it should be near the end of the file and it will only show the latest install attempt if you open the setup file again it will delete that log

**Comment by ziggmeisterr** [comment]
> you can also send part of its install log located at program files bloxshade and inside that folder install.txt and it should be near the end of the file and it will only show the latest install attempt if you open the setup file again it will delete that log

I just randomly tried it and it works now, thanks

**Comment by Extravi** [comment]
what anti virus are you using if I were to guess webroot?
