### ISSUE TITLE
error

### ISSUE THREAD

**Issue by coisasgamer4** [Extravi/Bloxshade#37]
![image](https://github.com/user-attachments/assets/cdf241a3-61f4-41d7-bccb-ba35e99ae892)
![image](https://github.com/user-attachments/assets/a9364907-7f29-43eb-abd3-0100dfe11087)

**Comment by Extravi** [comment]
reinstall roblox this is an issue related to bloxstrap not correctly uninstalling itself
https://github.com/pizzaboxer/bloxstrap/pull/1973
