### ISSUE TITLE
Shaders with hdr are VERY brightened up

### ISSUE THREAD

**Issue by Pvrb1e** [Extravi/Bloxshade#42]
if u put any shader with an HDR monitor it becomes very bright, it's not the screenshot bug where the screenshot looks brighter than what u see, it's the same as what I see as what I screenshotted:

with HDR (i turned down the brightness from the original so ur eyes don't die):
![image](https://github.com/user-attachments/assets/9db8978a-18e9-4f0b-b2f7-c60518fcc53c)
without HDR:
![image](https://github.com/user-attachments/assets/2b4703c0-f1cd-4599-a48f-427e839dcca2)

**Comment by Pvrb1e** [comment]
same shader same screen res and same screen, only toggled hdr and it made it wayy to bright for my eyes

**Comment by Pvrb1e** [comment]
on the day maps the sky is just bright blinding white

**Comment by Extravi** [comment]
it's because Nvidia Ansel doesn't have support for HDR displays nothing that I can do about it

**Comment by Pvrb1e** [comment]
maybe u could add an auto-disable hdr button when shader shortcuts are reset so when I add the shaders back it auto disables them
