### ISSUE TITLE
can't install.

### ISSUE THREAD

**Issue by Naplii** [Extravi/Bloxshade#44]
I have an issue with Bloxshade being stuck on the installation screen and I keep getting a warning saying "Roblox installation was not found. Do you want to download it?" it pops up every time I try to install Bloxshade. I already have RobloxPlayerInstaller.exe, which installs another Roblox player installer. Here are some screenshots.
![Screenshot 2024-09-17 164516](https://github.com/user-attachments/assets/1b83d744-9da7-4719-8c6f-4283633e213b)
![Screenshot 2024-09-17 164613](https://github.com/user-attachments/assets/34def6d8-5bd6-466b-93d9-22b91da902dd)

**Comment by Extravi** [comment]
run it as admin under your own user account your user account on windows cannot be a standard user and must be an admin user

**Comment by joshuathrasher** [comment]
uh i have a problem like my roblox runs fine whenever i install bloxshade in my roblox it doesnt run even as a admin whenever i reinstall roblox its good its only a problem whenever i download bloxshade and install.
