### ISSUE TITLE
"Microsoft edge can't read/write to it's data directory"

### ISSUE THREAD

**Issue by crzylemon** [Extravi/Bloxshade#51]
![image](https://github.com/user-attachments/assets/55d209d2-5279-4633-9708-f4870ef8cc8f)
don't know what's happening at all

**Comment by crzylemon** [comment]
Also, I can't run it on my own user, windows is forcing me to use admin permissions

**Comment by tikislizfr** [comment]
try using chrome or opera gx its better anyway

**Comment by Extravi** [comment]
run it as admin as your own user make sure your user account is an admin account
![image](https://github.com/user-attachments/assets/79de4d90-f123-4d05-b252-f70bbae2c3f6)
![image](https://github.com/user-attachments/assets/6fc1f657-d3d5-4a02-b3d9-4ec001d36468)

**Comment by Extravi** [comment]
bloxshade needs admin to download files to the nvidia folder for it to work
C:\Program Files\NVIDIA Corporation\Ansel
C:\Program Files\NVIDIA Corporation\Ansel\Custom
