### ISSUE TITLE
Bloxshade not Downloading

### ISSUE THREAD

**Issue by RealMetacomet** [Extravi/Bloxshade#55]
Whenever I try to download/update Bloxshade the string of code states: * Version: 2.8.15
* Bloxshade Installer (developed by Extravi, https://extravi.dev/)
* Copyright © 2024 Extravi
* Source Code: https://github.com/Extravi/Bloxshade
"C:\Users\[my name]\AppData\Local\Bloxstrap\Bloxstrap.exe" -player "%1"
Path to check: C:\Users\[my name]\AppData\Local\Bloxstrap\Bloxstrap.exe" -player "%1
Program files is false
Users path is true
Roblox install found
Bloxstrap is true
failed to open file
As  you can likely tell, I use Bloxstrap, and whenever I try to download Bloxshade with Bloxstrap installed, that error comes up. In addition, my Bloxstrap/Roblox launcher is set to be Roblox VR, and not Euro Truck Simulator 2. Please help.

**Comment by Extravi** [comment]
use the latest version of the installer 2.8.16
https://github.com/Extravi/Bloxshade/releases/tag/v2.8.16
