### ISSUE TITLE
Problems with downloading.

### ISSUE THREAD

**Issue by GlitchyEye** [Extravi/Bloxshade#56]
The installer sometimes just freezes and just sits doing nothing.
It freezes in random moments and I have no idea if it downloads a package or it doesnt (I would recommend adding a download meter 1%, 25%, 75% etc. if thats possible for you)
I had only 1 successful download of Bloxshade after waiting around 20 minutes and countless reinstalling of the installer.
Please fix.

**Comment by Extravi** [comment]
you might need to use a free vpn something like proton vpn might work or your anti virus is blocking it
