### ISSUE TITLE
Failed to open file

### ISSUE THREAD

**Issue by Subie1** [Extravi/Bloxshade#57]
Getting an error whenever trying to install (do any action it seems considering it does it to patching NVIDIA app aswell)

Log:
```
* Version: 2.8.15
* Bloxshade Installer (developed by Extravi, https://extravi.dev/)
* Copyright © 2024 Extravi
* Source Code: https://github.com/Extravi/Bloxshade
"C:\Users\Hp\AppData\Local\Bloxstrap\Bloxstrap.exe" -player "%1"
Path to check: C:\Users\Hp\AppData\Local\Bloxstrap\Bloxstrap.exe" -player "%1
Program files is false
Users path is true
Roblox install found
Bloxstrap is true
failed to open file
```

On Windows 11 with Bloxstrap and Roblox both latest versions of the time of creating this issue (Did a full Bloxstrap and Roblox uninstall multiple times)

**Comment by Extravi** [comment]
you're using the wrong version of the installer you have to use version 2.8.16 because older versions dont work with the latest version of bloxstrap https://github.com/Extravi/Bloxshade/releases/tag/v2.8.16
