### ISSUE TITLE
Unknown Publisher

### ISSUE THREAD

**Issue by Shane1013** [Extravi/Bloxshade#58]
I would recommend making a known publisher. It can be scary for some users to see "Unknown Publisher". Just a recommendation. If they don't look at the source code. Which I know people don't sometimes.

**Comment by Extravi** [comment]
that cost money to do it isn't free and its very expensive and i do not have the money to code sign
https://learn.microsoft.com/en-us/windows-hardware/drivers/dashboard/code-signing-cert-manage
