### ISSUE TITLE
Game crashes a few seconds after opening

### ISSUE THREAD

**Issue by RealNothing** [Extravi/Bloxshade#61]
I have bitdefender, but turning it off doesn't seem to fix it.

https://github.com/user-attachments/assets/06469f05-3e73-4653-8410-c03766baa64b

**Comment by Extravi** [comment]
what anti virus do you use?

**Comment by RealNothing** [comment]
> what anti virus do you use?

Bitdefender, but when turned off it still doesn't work

**Comment by Extravi** [comment]
bitdefender blocks roblox when its renamed to eurotrucks2.exe

**Comment by Extravi** [comment]
you need to exclude the fake RobloxPlayerBeta.exe and eurotrucks2.exe inside of the Roblox folder from the anti virus

**Comment by Extravi** [comment]
please update me if that solved your issue

**Comment by Extravi** [comment]
https://devforum.roblox.com/t/fix-roblox-not-opening-bitdefender-users-only/2661149

**Comment by RealNothing** [comment]
> please update me if that solved your issue

This fixed it. thank you

**Comment by Extravi** [comment]
thanks for letting me know
