### ISSUE TITLE
C++ Error

### ISSUE THREAD

**Issue by therealkiddude** [Extravi/Bloxshade#7]
![image_2024-05-07_153441929](https://github.com/Extravi/Bloxshade/assets/103710743/483779f4-90e4-46c8-9ee4-f7f33e1e084c)

**Comment by Extravi** [comment]
avast blocks the installer from downloading the files it needs

**Comment by mrrandom314** [comment]
> avast blocks the installer from downloading the files it needs

That's weird, I did not get a notification from Avast during the installation, but I will add an exception

**Comment by Extravi** [comment]
avast avg etc unlike other anti malware programs secretly block applications from using curl and they're the only programs that block curl

**Comment by mrrandom314** [comment]
> avast avg etc unlike other anti malware programs secretly block applications from using curl and they're the only programs that block curl

Should I whitelist just installer.exe or all the .exe files in Bloxshade's Program Files directory?

**Comment by Extravi** [comment]
no that wont work also i dont think you want to be using avast or avg https://www.ftc.gov/news-events/news/press-releases/2024/02/ftc-order-will-ban-avast-selling-browsing-data-advertising-purposes-require-it-pay-165-million-over

kaspersky cloud free or malwarebytes free is better or just use windows defender
https://www.kaspersky.com/downloads/free-antivirus
https://www.malwarebytes.com/mwb-download

> > avast avg etc unlike other anti malware programs secretly block applications from using curl and they're the only programs that block curl
> 
> Should I whitelist just installer.exe or all the .exe files in Bloxshade's Program Files directory?

**Comment by mrrandom314** [comment]
> no that wont work also i dont think you want to be using avast or avg https://www.ftc.gov/news-events/news/press-releases/2024/02/ftc-order-will-ban-avast-selling-browsing-data-advertising-purposes-require-it-pay-165-million-over
> 
> 
> 
> kaspersky cloud free or malwarebytes free is better or just use windows defender
> 
> https://www.kaspersky.com/downloads/free-antivirus
> 
> https://www.malwarebytes.com/mwb-download
> 
> 
> 
> > > avast avg etc unlike other anti malware programs secretly block applications from using curl and they're the only programs that block curl
> 
> > 
> 
> > Should I whitelist just installer.exe or all the .exe files in Bloxshade's Program Files directory?
> 
> 
> 
> 

I do have malwarebytes,a friend recommended avast to me, insane to hear that avast is suffering the same fate as Tiktok. Another person recommended not to use avast. Guess I'll delete avast!

**Comment by Extravi** [comment]
> > no that wont work also i dont think you want to be using avast or avg https://www.ftc.gov/news-events/news/press-releases/2024/02/ftc-order-will-ban-avast-selling-browsing-data-advertising-purposes-require-it-pay-165-million-over
> > kaspersky cloud free or malwarebytes free is better or just use windows defender
> > https://www.kaspersky.com/downloads/free-antivirus
> > https://www.malwarebytes.com/mwb-download
> > > > avast avg etc unlike other anti malware programs secretly block applications from using curl and they're the only programs that block curl
> > 
> > 
> > > 
> > 
> > 
> > > Should I whitelist just installer.exe or all the .exe files in Bloxshade's Program Files directory?
> 
> I do have malwarebytes,a friend recommended avast to me, insane to hear that avast is suffering the same fate as Tiktok. Another person recommended not to use avast. Guess I'll delete avast!

norton antivirus, avg, avast and avira antivirus are ALL software i would avoid because its owned by the same company that owns avast

**Comment by mrrandom314** [comment]
> > > no that wont work also i dont think you want to be using avast or avg https://www.ftc.gov/news-events/news/press-releases/2024/02/ftc-order-will-ban-avast-selling-browsing-data-advertising-purposes-require-it-pay-165-million-over
> > > kaspersky cloud free or malwarebytes free is better or just use windows defender
> > > https://www.kaspersky.com/downloads/free-antivirus
> > > https://www.malwarebytes.com/mwb-download
> > > > > avast avg etc unlike other anti malware programs secretly block applications from using curl and they're the only programs that block curl
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > Should I whitelist just installer.exe or all the .exe files in Bloxshade's Program Files directory?
> > 
> > 
> > I do have malwarebytes,a friend recommended avast to me, insane to hear that avast is suffering the same fate as Tiktok. Another person recommended not to use avast. Guess I'll delete avast!
> 
> norton antivirus, avg, avast and avira antivirus are ALL software i would avoid because its owned by the same company that owns avast

![image_2024-05-07_192754701](https://github.com/Extravi/Bloxshade/assets/103710743/b3605adc-1c3b-4fcd-86d7-0a1d383f8cc4)
